Repository ti-community-infra/ti-community-bot, pull requests merged in 2020-10, with the labels that each got.

#47 build: add dockerfile
  Dockerfile
  docker-compose.yml
Labels: status/can-merge

#49 ci: add release workflow
  .github/workflows/release.yml
  package-lock.json
  package.json
  release.config.js
Labels: status/can-merge

#50 fix: remove URL
  src/index.ts
Labels: status/can-merge

#53 fix: add URL
  src/index.ts
Labels: status/can-merge

#54 build: add npm release
  package.json
  release.config.js
Labels: status/can-merge

#59 feat: rename api
  .github/workflows/test.yml
  package.json
  src/api/pull/index.ts
  src/index.ts
  src/queries/PullOwnersQuery.ts
  src/services/dtos/PullOwnersDTO.ts
  src/services/dtos/PullReviewersDTO.ts
  src/services/pull/index.ts
  src/services/sig/index.ts
  src/services/utils/SigInfoUtils.ts
  test/api/pull/index.test.ts
Labels: status/can-merge

#64 test: add more cases
  .codecov.yml
  package-lock.json
  package.json
  src/events/pull/index.ts
  src/services/pull/index.ts
  src/services/utils/ReplyUtil.ts
  src/services/utils/SigInfoUtils.ts
  test/services/pull/index.test.ts
  test/services/utils/ReplyUtil.test.ts
  test/services/utils/SigInfoUtils.test.ts
Labels: status/can-merge

#66 chore: add README.md
  README.md
Labels: status/can-merge

#68 chore: add badge
  README.md
Labels: size/XS, status/can-merge

#69 fix: rename committer to approvers
  src/services/dtos/PullOwnersDTO.ts
  src/services/pull/index.ts
  test/api/pull/index.test.ts
  test/services/pull/index.test.ts
Labels: status/can-merge

#71 fix: refine reviewers when only fmt
  src/services/pull/index.ts
  test/services/pull/index.test.ts
Labels: size/M, status/can-merge

#73 fix: refine status
  src/services/pull/index.ts
  src/services/sig/index.ts
Labels: status/can-merge

#74 fix: refine gather
  package-lock.json
  package.json
  src/services/pull/index.ts
  src/services/utils/SigInfoUtils.ts
  test/services/pull/index.test.ts
Labels: size/XL, status/can-merge

#75 fix: remove email and company
  src/api/pull/index.ts
  src/config/SigInfoSchema.ts
  src/config/sig.info.schema.json
  src/services/messages/PullMessage.ts
  src/services/pull/index.ts
  src/services/sig/index.ts
  src/services/utils/SigInfoUtils.ts
  test/services/pull/index.test.ts
  test/services/sig/index.test.ts
  test/services/utils/SigInfoUtils.test.ts
Labels: size/XL, status/can-merge

#82 fix: report status for all PR
  src/events/pull/index.ts
  src/services/messages/PullMessage.ts
  src/services/pull/index.ts
  test/services/pull/index.test.ts
Labels: size/S, status/can-merge

#95 feat: impl sig api
  package-lock.json
  package.json
  src/api/pull/index.ts
  src/api/sig/index.ts
  src/events/pull/index.ts
  src/index.ts
  src/repositoies/sig-member/index.ts
  src/services/dtos/SigDTO.ts
  src/services/messages/SigMessage.ts
  src/services/pull/index.ts
  src/services/sig/index.ts
  test/api/pull/index.test.ts
  test/api/sig/index.test.ts
  test/services/pull/index.test.ts
  test/services/sig/index.test.ts
Labels: size/XL, status/can-merge
