Repository ti-community-infra/ti-community-bot, pull requests merged in 2020-11, with the labels that each got.

#106 fix: only update info
  src/services/sig/index.ts
  test/services/sig/index.test.ts
Labels: size/M, status/can-merge

#109 fix: rename approver to committer
  src/services/dtos/PullOwnersDTO.ts
  src/services/pull/index.ts
  test/api/pull/index.test.ts
  test/services/pull/index.test.ts
Labels: size/M

#110 fix: support delete members
  src/services/sig/index.ts
  test/services/sig/index.test.ts
Labels: size/L, status/can-merge

#112 fix: only comment once
  src/events/pull/index.ts
  src/services/messages/PullMessage.ts
Labels: size/M

#116 feat: support list owbers by sig label
  src/api/pull/index.ts
  src/queries/LabelQuery.ts
  src/queries/PullOwnersQuery.ts
  src/services/pull/index.ts
  src/services/utils/SigInfoUtils.ts
  test/api/pull/index.test.ts
  test/services/pull/index.test.ts
  test/services/utils/SigInfoUtils.test.ts
Labels: size/L, status/can-merge

#140 chore: use escape double quotation marks for windows
  package.json
Labels: size/XS, status/LGT1, status/can-merge

#141 fix: limit the collaborators LGTM and Merge permission
  src/api/pull/index.ts
  src/config/SigInfoSchema.ts
  src/services/pull/index.ts
  test/api/pull/index.test.ts
  test/services/pull/index.test.ts
Labels: size/L, status/LGT1, status/can-merge
